name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Print Greeting
        run: echo "hello world"
      - name: Print Goodbye
        run: echo "done, bye"
