name: Output event details on issue
on: [issues, workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
