name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # this will make github continue executing jobs related to the matrix even if some others failed
    strategy:
      matrix:
        # matrix strategy means job is executed for each permutation of keys below
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # include is a special key that is not treated as a matrix combination but rather as a additional run
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # exclude is a special key that skips execution for the particular combination
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        working-directory: client
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build