name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Output github context
        run: echo "${{ toJSON(github) }}"